import Head from 'next/head';
import { Inter } from 'next/font/google';
import styled from 'styled-components';
import Sales from '@/components/Sales';
import SalesActivities from '@/components/SalesActivities';
import LastOrders from '@/components/LastOrders';
import TopPlatform from '@/components/TopPlatform';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Geegpay Challenge</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/favicon.ico"
                />
            </Head>
            <MainContent>
                <Sales />
                <div className="sales--activities">
                    {salesActivities.map((item, index) => (
                        <SalesActivities
                            key={index}
                            activity={item}
                        />
                    ))}
                </div>
                <LastOrders />
                <TopPlatform />
            </MainContent>
        </>
    );
}

const MainContent = styled.section`
    display: grid;
    grid-template-columns: repeat(12, 1fr);
    gap: 2rem;
    width: 100%;
    padding-inline: 1rem;
    background-color: ${(p) => p.theme.bgColor};

    .sales--activities {
        grid-column: 8/13;
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 1.6rem;
    }

    @media screen and (max-width: 1200px) {
        width: 100%;
        display: flex;
        flex-direction: column;
        .sales--activities {
        }
    }

    @media screen and (max-width: 600px) {
        .sales--activities {
            display: flex;
            flex-direction: column;
        }
    }
`;

const salesActivities = [
    {
        icon: 'order.svg',
        title: 'Total Order',
        amount: 330,
        percent: 23.5,
        uptrend: true,
    },
    {
        icon: 'refund.svg',
        title: 'Total Order',
        amount: 460,
        percent: 23.5,
        uptrend: false,
    },
    {
        icon: 'sales.svg',
        title: 'Total Order',
        amount: 350,
        percent: 23.5,
        uptrend: false,
    },
    {
        icon: 'income.svg',
        title: 'Total Order',
        amount: 120,
        percent: 23.5,
        uptrend: true,
    },
];
